name: Publish to NPM

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check AT_TOKEN Secret
        run: |
          if [[ -n "$AT_TOKEN" ]]; then
            echo "AT_TOKEN: YES"
          else
            echo "AT_TOKEN: NO"
          fi
        env:
          AT_TOKEN: ${{ secrets.AT_TOKEN }}

      - name: Check NPM_AUTOMATION_TOKEN Secret
        run: |
          if [[ -n "$NPM_AUTOMATION_TOKEN" ]]; then
            echo "NPM_AUTOMATION_TOKEN: YES"
          else
            echo "NPM_AUTOMATION_TOKEN: NO"
          fi
        env:
          NPM_AUTOMATION_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
      - run: npm ci
      - run: npm run build
      - name: Run Semantic Release
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.AT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
